const data = [
  {
    "S/N": 1,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Abacha",
    imageSrc: "/aboniki.png",
    Quantity: 43,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7556780086558,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$3.00",
  },
  {
    "S/N": 2,
    "Brand Name": "Aboniki",
    "Product Name": "Aboniki Balm",
    Quantity: 9,
    imageSrc: "/aboniki.png",
    "Weight (lb)": "-",
    "Weight (kg)": "25g",
    Size: "-",
    "Barcode No/ Product ID": 6156000046105,
    Category: "",
    "Exipry Date (M-Y)": "May-24",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 3,
    "Brand Name": "Aboniki",
    imageSrc: "/aboniki-box.jpeg",
    "Product Name": "Aboniki Balm (Box)",
    Quantity: 2,
    "Weight (lb)": "-",
    "Weight (kg)": "25g/Bottle",
    Size: "48 Bottles/Box",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "May-24",
    "Unit Price": "-",
  },
  {
    "S/N": 5,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Achi",
    Quantity: 5,
    "Weight (lb)": "-",
    "Weight (kg)": "500g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 7,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "African Native Honey",
    Quantity: 29,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "50cl",
    "Barcode No/ Product ID": 8880225673454,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 8,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "African Native Honey",
    Quantity: 17,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "100cl",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "",
    "Unit Price": "$10.00",
  },
  {
    "S/N": 9,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Alum",
    Quantity: 3,
    "Weight (lb)": "-",
    "Weight (kg)": "39kg/Bag",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "3 for $10",
  },
  {
    "S/N": 10,
    "Brand Name": "Dettol",
    imageSrc: "/dettol-pack.jpeg",
    "Product Name": "Antibacterial Soap (Box)",
    Quantity: 3,
    "Weight (lb)": "-",
    "Weight (kg)": "65g/Bar",
    Size: "144 Bars/Box",
    "Barcode No/ Product ID": "-",
    Category: "-",
    "Exipry Date (M-Y)": "Nov-22",
    "Unit Price": "",
  },
  {
    "S/N": 11,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ataare",
    Quantity: 1,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "100 Pieces",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$6.00",
  },
  {
    "S/N": 12,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ayamase",
    Quantity: 6,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "4 Litres",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$30.00",
  },
  {
    "S/N": 13,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ayamase",
    Quantity: 6,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "2 Litres",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$15.00",
  },
  {
    "S/N": 14,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ayo (Game)",
    Quantity: 20,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Game",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$15.00",
  },
  {
    "S/N": 15,
    "Brand Name": "Heinz Beans",
    "Product Name": "Baked Beans",
    imageSrc: "/heinz_baked_bean.jpeg",
    Quantity: 12,
    "Weight (lb)": "-",
    "Weight (kg)": "200g",
    Size: "-",
    "Barcode No/ Product ID": 6290090017000,
    Category: "",
    "Exipry Date (M-Y)": "Oct-23",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 16,
    "Brand Name": "Pally Agro",
    "Product Name": "Banga",
    imageSrc: "/banga_pally.jpeg",
    Quantity: 12,
    "Weight (lb)": "-",
    "Weight (kg)": "800g",
    Size: "-",
    "Barcode No/ Product ID": 6156000214504,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$10.00",
  },
  {
    "S/N": 18,
    "Brand Name": "Okomu",
    "Product Name": "Banga Red Palm Oil",
    Quantity: 5,
    imageSrc: "/banga_red_oil.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "2 Litres",
    "Barcode No/ Product ID": 6152110062721,
    Category: "",
    "Exipry Date (M-Y)": "Mar-23",
    "Unit Price": "$12.00",
  },
  {
    "S/N": 20,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Banga Soup Spice",
    Quantity: 12,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7553380029985,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 21,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Banga Soup Spice",
    Quantity: 24,
    "Weight (lb)": "-",
    "Weight (kg)": "300g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$10.00",
  },
  {
    "S/N": 202,
    "Brand Name": "Dettol",
    "Product Name": "Bar Soap + Liquid (Economy Pack)",
    Quantity: 36,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "165ml",
    "Barcode No/ Product ID": 6009695935400,
    Category: "Soap",
    "Exipry Date (M-Y)": "Nov-23",
    "Unit Price": "$6.00",
  },
  {
    "S/N": 22,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Beans Flour",
    Quantity: 35,
    "Weight (lb)": 1.1,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 9665870862564,
    Category: "Flour",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$2.00",
  },
  {
    "S/N": 23,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Beans Flour",
    Quantity: 68,
    "Weight (lb)": 2.2,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 8800025667491,
    Category: "Flour",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$4.00",
  },
  {
    "S/N": 24,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Bitter Kola",
    Quantity: 14,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 25,
    "Brand Name": "Awa Golden",
    imageSrc: "/awa_golden.webp",
    "Product Name": "Black Soap",
    Quantity: 115,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Soap",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 26,
    "Brand Name": "Dudu Osun",
    "Product Name": "Black Soap",
    imageSrc: "/dudu_osun.jpeg",
    Quantity: 24,
    "Weight (lb)": "-",
    "Weight (kg)": "150g",
    Size: "-",
    "Barcode No/ Product ID": 6156000043708,
    Category: "Soap",
    "Exipry Date (M-Y)": "Sep-23",
    "Unit Price": "$4.00",
  },
  {
    "S/N": 28,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Black Soap (Ghana)",
    Quantity: 33,
    "Weight (lb)": "-",
    "Weight (kg)": "120g",
    Size: "-",
    "Barcode No/ Product ID": 7551180029983,
    Category: "Soap",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 30,
    "Brand Name": "Vicks",
    "Product Name": "Blue (Box)",
    Quantity: 1,
    imageSrc: "/vicks_blue_box.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "24 Bags/Box",
    "Barcode No/ Product ID": "-",
    Category: "Sweets",
    "Exipry Date (M-Y)": "Apr-22",
    "Unit Price": "$25.00",
  },

  {
    "S/N": 32,
    "Brand Name": "Cadbury",
    "Product Name": "Bournvita",
    Quantity: 6,
    imageSrc: "/bournvita.webp",
    "Weight (lb)": "-",
    "Weight (kg)": "900g",
    Size: "-",
    "Barcode No/ Product ID": 7622210492135,
    Category: "Beverage",
    "Exipry Date (M-Y)": "May-23",
    "Unit Price": "$17.00",
  },

  {
    "S/N": 35,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Brown Beans (Drum)",
    Quantity: 51,
    "Weight (lb)": 2.2,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7551180029983,
    Category: "Beans",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$6.00",
  },
  {
    "S/N": 36,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Brown Beans (Milk)",
    Quantity: 29,
    "Weight (lb)": 2.2,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7552280029989,
    Category: "Beans",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 37,
    "Brand Name": "McVitie's",
    "Product Name": "Butter Shortbread",
    Quantity: "-",
    imageSrc: "/shortbread.webp",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 5000168008967,
    Category: "Biscuit",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$4.00",
  },
  //   {
  //     "S/N": 38,
  //     "Brand Name": "Cadbury",
  //     "Product Name": "Buttermint",
  //     imageSrc: "/buttermint.jpeg",
  //     Quantity: 18,
  //     "Weight (lb)": "-",
  //     "Weight (kg)": "-",
  //     Size: "40 Sweets/Bag",
  //     "Barcode No/ Product ID": 7622210564924,
  //     Category: "Sweets",
  //     "Exipry Date (M-Y)": "May-22",
  //     "Unit Price": "$5.00",
  //   },
  {
    "S/N": 39,
    "Brand Name": "Cadbury",
    "Product Name": "Buttermint (Box)",
    Quantity: 1,
    "Weight (lb)": "-",
    "Weight (kg)": "152g/Bag",
    Size: "26 Bags/Box",
    "Barcode No/ Product ID": "-",
    Category: "Sweets",
    "Exipry Date (M-Y)": "May-22",
    "Unit Price": "$25.00",
  },
  {
    "S/N": 40,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Cameroun Pepper",
    Quantity: 87,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7556780088866,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 41,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Camphor",
    Quantity: 2,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$10.00",
  },
  {
    "S/N": 42,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Cassava Flour (Lafun)",
    Quantity: 8,
    "Weight (lb)": 5.5,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 8880225673461,
    Category: "Flour",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$10.00",
  },
  {
    "S/N": 43,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Cassava Flour (Lafun)",
    Quantity: 76,
    "Weight (lb)": 2.2,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 8880225673454,
    Category: "Flour",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 44,
    "Brand Name": "Fun Snax",
    "Product Name": "Cheese Balls",
    imageSrc: "/cheese_balls.jpeg",
    Quantity: "-",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 8906028819513,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 45,
    "Brand Name": "Knorr",
    "Product Name": "Chicken Seasoning Cubes (Box)",
    imageSrc: "/knorr.jpg",
    Quantity: 4,
    "Weight (lb)": "-",
    "Weight (kg)": "8g/Cube",
    Size: "50 Cubes/Pack 17 Packs/Box",
    "Barcode No/ Product ID": "06154000153816",
    Category: "",
    "Exipry Date (M-Y)": "Dec-22",
    "Unit Price": "$130.00",
  },
  //   {
  //     "S/N": 46,
  //     "Brand Name": "Knorr",
  //     "Product Name": "Chicken Seasoning Cubes (Pack)",
  //     Quantity: 14,
  //     "Weight (lb)": "-",
  //     "Weight (kg)": "8g/Cube",
  //     Size: "50 Cubes/Pack",
  //     "Barcode No/ Product ID": 6154000153724,
  //     Category: "",
  //     "Exipry Date (M-Y)": "Dec-22",
  //     "Unit Price": "$13.99",
  //   },
  {
    "S/N": 47,
    "Brand Name": "His Grace",
    "Product Name": "Chin Chin",
    Quantity: 96,
    imageSrc: "/his-grace.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Chin Chin",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 48,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Cloves",
    Quantity: 28,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 49,
    "Brand Name": "Newbisco",
    "Product Name": "Coasters",
    imageSrc: "/coaster_biscuit.jpeg",
    Quantity: "-",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Biscuit",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 50,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Cocoyam (Ede)",
    Quantity: 9,
    "Weight (lb)": 1.1,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 51,
    "Brand Name": "Sarah",
    "Product Name": "Coloured Prawn Crackers (Box)",
    imageSrc: "/prawn_crackers.jpeg",
    Quantity: 30,
    "Weight (lb)": "-",
    "Weight (kg)": "227g",
    Size: "-",
    "Barcode No/ Product ID": 6921325101309,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$4.99",
  },
  //   {
  //     "S/N": 52,
  //     "Brand Name": "Sarah",
  //     "Product Name": "Coloured Prawn Crackers (Box)",
  //     Quantity: 1,

  //     "Weight (lb)": "-",
  //     "Weight (kg)": "-",
  //     Size: "30 Pieces/Box",
  //     "Barcode No/ Product ID": 6921325101316,
  //     Category: "",
  //     "Exipry Date (M-Y)": "-",
  //     "Unit Price": "$150.00",
  //   },
  {
    "S/N": 53,
    "Brand Name": "Dettol",
    "Product Name": "Cool Antibacterial Bar Soap",
    Quantity: 60,
    imageSrc: "/dettol-cool.png",
    "Weight (lb)": "-",
    "Weight (kg)": "110g",
    Size: "-",
    "Barcode No/ Product ID": 6151100280503,
    Category: "Soap",
    "Exipry Date (M-Y)": "Nov-22",
    "Unit Price": "$3.00",
  },
  {
    "S/N": 54,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Corn Grit",
    Quantity: 72,
    "Weight (lb)": 2.2,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 9665870662379,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 55,
    "Brand Name": "Exeter",
    "Product Name": "Corned Beef",
    imageSrc: "/Exeter_Corned_Beef.png",
    Quantity: 24,
    "Weight (lb)": "-",
    "Weight (kg)": "340g",
    Size: "-",
    "Barcode No/ Product ID": 7790360967152,
    Category: "",
    "Exipry Date (M-Y)": "Nov-24",
    "Unit Price": "$5.00",
  },
  //   {
  //     "S/N": 56,
  //     "Brand Name": "Exeter",
  //     "Product Name": "Corned Beef",
  //     Quantity: 24,
  //     "Weight (lb)": "-",
  //     "Weight (kg)": "200g",
  //     Size: "-",
  //     "Barcode No/ Product ID": 3173820003258,
  //     Category: "",
  //     "Exipry Date (M-Y)": "May-24",
  //     "Unit Price": "$2.99",
  //   },
  {
    "S/N": 57,
    "Brand Name": "Exeter",
    "Product Name": "Corned Beef (Box)",
    Quantity: 1,
    "Weight (lb)": "-",
    "Weight (kg)": "200g/Cases",
    Size: "24 Cases/Box",
    "Barcode No/ Product ID": 15060178692966,
    Category: "",
    "Exipry Date (M-Y)": "May-24",
    "Unit Price": "",
  },
  {
    "S/N": 58,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Crayfish (Grounded)",
    Quantity: 9,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 59,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Crayfish (Grounded)",
    Quantity: 127,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7556780029937,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 60,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Crayfish (Grounded)",
    Quantity: 145,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7555780086650,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 61,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Crayfish (Ungrounded)",
    Quantity: 55,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7556780029937,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 62,
    "Brand Name": "Beloxxi",
    "Product Name": "Cream Crackers",
    imageSrc: "/beloxxi.jpeg",
    Quantity: "-",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Biscuit",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 63,
    "Brand Name": "Kemps",
    imageSrc: "/kemps.png",
    "Product Name": "Cream Creackers",
    Quantity: "-",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Biscuit",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 64,
    "Brand Name": "Ducros",
    "Product Name": "Curry Powder",
    Quantity: 132,
    imageSrc: "/ducros_curry.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "25g/Bottle",
    Size: "-",
    "Barcode No/ Product ID": 3275920039165,
    Category: "",
    "Exipry Date (M-Y)": "Nov-23",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 66,
    "Brand Name": "Ducros",
    "Product Name": "Curry Powder (Box)",
    Quantity: 3,
    imageSrc: "/ducros_curry.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "25g/Bottle",
    Size: "12 Bottles/Pack 12 Packs/Box",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "Oct-23",
    "Unit Price": "$144.00",
  },
  {
    "S/N": 65,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Curry Powder",
    Quantity: 59,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7554480029981,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },

  // {
  //   "S/N": 67,
  //   "Brand Name": "Checkers",
  //   "Product Name": "Custard Powder",
  //   Quantity: 12,
  //   imageSrc: "/ducros_curry.jpeg",
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "400g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6152110065975,
  //   Category: "Custard",
  //   "Exipry Date (M-Y)": "May-23",
  //   "Unit Price": "$3.50",
  // },
  {
    "S/N": 68,
    "Brand Name": "Checkers",
    "Product Name": "Custard Powder",
    imageSrc: "/checkers_custard.jpeg",
    Quantity: 34,
    "Weight (lb)": "-",
    "Weight (kg)": "400g",
    Size: "-",
    "Barcode No/ Product ID": 6152110065975,
    Category: "Custard",
    "Exipry Date (M-Y)": "Apr-23",
    "Unit Price": "$3.50",
  },
  {
    "S/N": 69,
    "Brand Name": "Lady B",
    "Product Name": "Custard Powder",
    Quantity: 4,
    imageSrc: "/lady_b.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "2kg",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Custard",
    "Exipry Date (M-Y)": "Nov-22",
    "Unit Price": "$10.00",
  },

  //   {
  //     "S/N": 71,
  //     "Brand Name": "Lady B",
  //     "Product Name": "Custard Powder",
  //     Quantity: 69,
  //     "Weight (lb)": "-",
  //     "Weight (kg)": "500g",
  //     Size: "-",
  //     "Barcode No/ Product ID": "-",
  //     Category: "Custard",
  //     "Exipry Date (M-Y)": "Apr-23",
  //     "Unit Price": "$5.00",
  //   },
  {
    "S/N": 72,
    "Brand Name": "Checkers",
    "Product Name": "Custard Powder (Banana Flavour)",
    Quantity: 3,
    imageSrc: "/checkers-custard.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "2kg",
    Size: "-",
    "Barcode No/ Product ID": "0714084852690",
    Category: "Custard",
    "Exipry Date (M-Y)": "Jul-22",
    "Unit Price": "$10.00",
  },
  //   {
  //     "S/N": 73,
  //     "Brand Name": "Checkers",
  //     "Product Name": "Custard Powder (Vanilla Flavour)",
  //     Quantity: 3,
  //     "Weight (lb)": "-",
  //     "Weight (kg)": "2kg",
  //     Size: "-",
  //     "Barcode No/ Product ID": 6152110065968,
  //     Category: "Custard",
  //     "Exipry Date (M-Y)": "Sep-22",
  //     "Unit Price": "$10.00",
  //   },
  //   {
  //     "S/N": 74,
  //     "Brand Name": "Checkers",
  //     "Product Name": "Custard Powder (Vanilla Flavour)",
  //     Quantity: 12,
  //     "Weight (lb)": "-",
  //     "Weight (kg)": "400g",
  //     Size: "-",
  //     "Barcode No/ Product ID": 6152110065975,
  //     Category: "Custard",
  //     "Exipry Date (M-Y)": "Apr-23",
  //     "Unit Price": "$3.50",
  //   },
  //   {
  //     "S/N": 75,
  //     "Brand Name": "Checkers",
  //     "Product Name": "Custard Powder (Vanilla Flavour)",
  //     Quantity: 24,
  //     "Weight (lb)": "-",
  //     "Weight (kg)": "400g",
  //     Size: "-",
  //     "Barcode No/ Product ID": 737297000115,
  //     Category: "Custard",
  //     "Exipry Date (M-Y)": "May-23",
  //     "Unit Price": "$3.50",
  //   },
  {
    "S/N": 76,
    "Brand Name": "McVitie's",
    "Product Name": "Digestive",
    imageSrc: "/digestive.jpeg",
    Quantity: "-",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Biscuit",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 77,
    "Brand Name": "Ducros",
    "Product Name": "Dried Thyme",
    imageSrc: "/thyme-ducros.jpeg",
    Quantity: 144,
    "Weight (lb)": "-",
    "Weight (kg)": "10g/Bottle",
    Size: "-",
    "Barcode No/ Product ID": 3275920039158,
    Category: "",
    "Exipry Date (M-Y)": "Oct-23",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 78,
    "Brand Name": "Ducros",
    "Product Name": "Dried Thyme (Box)",
    imageSrc: "/thyme-box.jpeg",
    Quantity: 2,
    "Weight (lb)": "-",
    "Weight (kg)": "10g/Bottle",
    Size: "12 Bottles/Pack 12 Packs/Box",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "Oct-23",
    "Unit Price": "$144.00",
  },
  {
    "S/N": 79,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Dry Bitter Leaves",
    Quantity: 52,
    "Weight (lb)": "-",
    "Weight (kg)": "60g",
    Size: "-",
    "Barcode No/ Product ID": 7555780068656,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 80,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Dry Ewedu Leaves",
    Quantity: 25,
    "Weight (lb)": "-",
    "Weight (kg)": "60g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 81,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Dry Ugu Leaves",
    Quantity: 29,
    "Weight (lb)": "-",
    "Weight (kg)": "60g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 82,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Dry Utazi Leaves",
    Quantity: 20,
    "Weight (lb)": "-",
    "Weight (kg)": "60g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 83,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Efinrin",
    Quantity: 20,
    "Weight (lb)": "-",
    "Weight (kg)": "60g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 84,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Egusi (Grounded)",
    Quantity: 66,
    "Weight (lb)": 1.1,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7556780026660,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$7.99",
  },
  {
    "S/N": 85,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Egusi (Ungrounded)",
    Quantity: 60,
    "Weight (lb)": 1.1,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7556680029969,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 86,
    "Brand Name": "Spice Supreme",
    "Product Name": "Fried Rice Spice",
    Quantity: 12,
    "Weight (lb)": "-",
    imageSrc: "/spice_fried_rice.jpeg",
    "Weight (kg)": "121g",
    Size: "-",
    "Barcode No/ Product ID": "076114305140",
    Category: "",
    "Exipry Date (M-Y)": "Oct-23",
    "Unit Price": "$6.00",
  },
  {
    "S/N": 87,
    "Brand Name": "Maliban",
    "Product Name": "Gem Sweet Biscuits",
    Quantity: "-",
    imageSrc: "/gem_sweet_biscuit.webp",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 4791034026116,
    Category: "Biscuit",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$2.50",
  },
  // {
  //   "S/N": 88,
  //   "Brand Name": "Mama Chev",
  //   "Product Name": "Ginger Powder",
  //   Quantity: 56,
  //   imageSrc: "/gem_sweet_biscuit.webp",
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "80g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 7885569965563,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Apr-23",
  //   "Unit Price": "$5.00",
  // },
  {
    "S/N": 89,
    "Brand Name": "Grain Process Enterprises Ltd",
    "Product Name": "Gold King Wheatlets",
    Quantity: 3,
    "Weight (lb)": 22,
    imageSrc: "/golden_wheat.jpeg",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Wheatlets",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$24.00",
  },
  {
    "S/N": 90,
    "Brand Name": "Nestle",
    "Product Name": "Golden Morn",
    Quantity: 9,
    imageSrc: "/Nestle-Golden-Morn-1-Kg-Bag-1.jpg.webp",
    "Weight (lb)": "-",
    "Weight (kg)": "900g",
    Size: "-",
    "Barcode No/ Product ID": 6151100037312,
    Category: "",
    "Exipry Date (M-Y)": "Sep-22",
    "Unit Price": "$16.99",
  },
  // {
  //   "S/N": 91,
  //   "Brand Name": "Nestle",
  //   "Product Name": "Golden Morn",
  //   Quantity: 52,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "450g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6151100035646,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Sep-22",
  //   "Unit Price": "$10.99",
  // },
  {
    "S/N": 92,
    "Brand Name": "Damatol",
    "Product Name": "Hair, Scalp, Skin Treatment",
    Quantity: 6,
    imageSrc: "/damatol.jpg",
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Cream",
    "Exipry Date (M-Y)": "Feb-24",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 93,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Hot Chilly Pepper",
    Quantity: 27,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 94,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Hot Chilly Pepper",
    Quantity: 173,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7555780027653,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 95,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Igbako (Plastic)",
    Quantity: 45,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "-",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 96,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Igbako (Wooden)",
    Quantity: 96,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "-",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 97,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ijebu Garri",
    Quantity: 30,
    "Weight (lb)": 5.5,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7556680029976,
    Category: "Garri",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$10.00",
  },
  {
    "S/N": 98,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ijebu Garri",
    Quantity: 49,
    "Weight (lb)": 2.2,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7556680029983,
    Category: "Garri",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$6.00",
  },
  {
    "S/N": 99,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ijebu Garri",
    Quantity: 84,
    "Weight (lb)": 1.1,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7556780086657,
    Category: "Garri",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$2.00",
  },
  {
    "S/N": 100,
    "Brand Name": "Indomie",
    "Product Name": "Indomie Chicken Flavour",
    Quantity: 4,
    imageSrc: "/71pbxHy0E8L._AC_SL1500_.jpg",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "40/Box",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "Oct-22",
    "Unit Price": "$20.00",
  },
  {
    "S/N": 101,
    "Brand Name": "Indomie",
    "Product Name": "Indomie Onion Chicken Flavour",
    Quantity: 5,
    imageSrc: "/Indomietable-Onion-70g.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "40/Box",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "Oct-22",
    "Unit Price": "$20.00",
  },
  // {
  //   "S/N": 102,
  //   "Brand Name": "Checkers",
  //   "Product Name": "Instant Milk Custard",
  //   Quantity: 3,
  //   imageSrc: "/checkers_insant_milk.jpeg",
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "1.5kg",
  //   Size: "-",
  //   "Barcode No/ Product ID": "0714084860084",
  //   Category: "Custard",
  //   "Exipry Date (M-Y)": "Nov-22",
  //   "Unit Price": "$10.00",
  // },
  {
    "S/N": 103,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Iyere",
    Quantity: 10,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 104,
    "Brand Name": "Jet",
    imageSrc: "/jet_cream.png",
    "Product Name": "Jet Cream",
    Quantity: 6,
    "Weight (lb)": "-",
    "Weight (kg)": "125g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Cream",
    "Exipry Date (M-Y)": "Feb-24",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 105,
    "Brand Name": "Supreme Spice",
    imageSrc: "/jollof_rice_spice.jpeg",
    "Product Name": "Jollof Rice Spice",
    Quantity: 12,
    "Weight (lb)": "-",
    "Weight (kg)": "151g",
    Size: "-",
    "Barcode No/ Product ID": "076114305263",
    Category: "",
    "Exipry Date (M-Y)": "Nov-23",
    "Unit Price": "$6.00",
  },
  {
    "S/N": 106,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Jollof Rice Spice",
    Quantity: 96,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7555780023655,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 107,
    "Brand Name": "Ademoy",
    imageSrc: "/killishi.webp",
    "Product Name": "Kilishi",
    Quantity: 18,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "Jan-23",
    "Unit Price": "$14.00",
  },
  {
    "S/N": 108,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Koun",
    Quantity: 11,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$2.00",
  },
  // {
  //   "S/N": 109,
  //   "Brand Name": "Bande's Groundnut Cookies",
  //   "Product Name": "Kuli Kuli",
  //   imageSrc: "/killishi.webp",
  //   Quantity: 89,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "Kuli Kuli",
  //   "Exipry Date (M-Y)": "Dec-22",
  //   "Unit Price": "$1.00",
  // },
  {
    "S/N": 110,
    "Brand Name": "Krizpi",
    "Product Name": "Kuli Kuli",
    Quantity: 99,
    imageSrc: "/krizpi.png",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 6156000289908,
    Category: "Kuli Kuli",
    "Exipry Date (M-Y)": "Apr-22",
    "Unit Price": "$1.00",
  },
  {
    "S/N": 111,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Kuli Kuli",
    Quantity: 3,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7552280029989,
    Category: "Kuli Kuli",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  // {
  //   "S/N": 112,
  //   "Brand Name": "Vicks",
  //   imageSrc: "/lemon_plus.webp",
  //   "Product Name": "Lemon Plus",
  //   Quantity: 21,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "30 Sweets/Bag",
  //   "Barcode No/ Product ID": 5000174823677,
  //   Category: "Sweets",
  //   "Exipry Date (M-Y)": "Apr-22",
  //   "Unit Price": "$5.00",
  // },
  {
    "S/N": 113,
    "Brand Name": "Vicks",
    "Product Name": "Lemon Plus (Box)",
    Quantity: 2,
    imageSrc: "/lemon_plus.webp",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "24 Bags/Box",
    "Barcode No/ Product ID": "-",
    Category: "Sweets",
    "Exipry Date (M-Y)": "Apr-22",
    "Unit Price": "$25.00",
  },
  {
    "S/N": 114,
    "Brand Name": "Lion",
    imageSrc: "/lion_card.webp",
    "Product Name": "Lion Cards (Game)",
    Quantity: 12,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Game",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 115,
    "Brand Name": "Dettol",
    "Product Name": "Liquid Antiseptic",
    imageSrc: "/dettol-antiseptic-liquid-1l.jpeg",
    Quantity: 22,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "500ml",
    "Barcode No/ Product ID": 50158089,
    Category: "Soap",
    "Exipry Date (M-Y)": "Mar-24",
    "Unit Price": "$10.00",
  },
  {
    "S/N": 116,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Local Sponge",
    Quantity: 30,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "-",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 117,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Locus Bean",
    Quantity: 77,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7000556665787,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 118,
    "Brand Name": "Ludo",
    "Product Name": "Ludo (Game)",
    imageSrc: "/ludo.jpg",
    Quantity: 10,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Game",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$15.00",
  },
  // {
  //   "S/N": 119,
  //   "Brand Name": "Maggi",

  //   "Product Name": "Maggi Chicken Flavour Seasoning (Pack)",
  //   Quantity: 19,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "10g/Cube",
  //   Size: "60 Cubes/Pack",
  //   "Barcode No/ Product ID": 6151100034465,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Sep-22",
  //   "Unit Price": "$8.00",
  // },
  {
    "S/N": 120,
    "Brand Name": "Maggi",
    imageSrc: "/maggi.webp",
    "Product Name": "Maggi Star Seasoning (Pack)",
    Quantity: 20,
    "Weight (lb)": "-",
    "Weight (kg)": "400g",
    Size: "100 Cubes/Pack",
    "Barcode No/ Product ID": 6151100034786,
    Category: "",
    "Exipry Date (M-Y)": "Dec-22",
    "Unit Price": "$7.50",
  },
  {
    "S/N": 121,
    "Brand Name": "Malta",
    "Product Name": "Maltex (Pack)",
    imageSrc: "/maltex.webp",
    Quantity: 5,
    "Weight (lb)": "-",
    "Weight (kg)": "330ml/Bottle",
    Size: "24 Bottles/Pack",
    "Barcode No/ Product ID": "008361271015",
    Category: "Drinks",
    "Exipry Date (M-Y)": "Feb-23",
    "Unit Price": "$3.00",
  },
  {
    "S/N": 122,
    "Brand Name": "Tetmosol",
    imageSrc: "/tetmosol.webp",
    "Product Name": "Medicated Soap",
    Quantity: 72,
    "Weight (lb)": "-",
    "Weight (kg)": "75g",
    Size: "-",
    "Barcode No/ Product ID": 6009826820018,
    Category: "Soap",
    "Exipry Date (M-Y)": "Jun-24",
    "Unit Price": "$2.00",
  },
  {
    "S/N": 123,
    "Brand Name": "Tura",
    imageSrc: "/tura.jpg",
    "Product Name": "Medicated Soap",
    Quantity: 48,
    "Weight (lb)": "-",
    "Weight (kg)": "65g",
    Size: "-",
    "Barcode No/ Product ID": 6156000060118,
    Category: "Soap",
    "Exipry Date (M-Y)": "Nov-23",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 124,
    "Brand Name": "Tetmosol",
    imageSrc: "/tetmosol_pack.jpg",
    "Product Name": "Medicated Soap (Box)",
    Quantity: 2,
    "Weight (lb)": "-",
    "Weight (kg)": "75g/Bar",
    Size: "72 Bars/Box",
    "Barcode No/ Product ID": "-",
    Category: "Soap",
    "Exipry Date (M-Y)": "Jun-24",
    "Unit Price": "",
  },
  {
    "S/N": 125,
    "Brand Name": "Peak",
    imageSrc: "/peak_milk.jpeg",
    "Product Name": "Milk",
    Quantity: 12,
    "Weight (lb)": "-",
    "Weight (kg)": "900g",
    Size: "-",
    "Barcode No/ Product ID": 8716200478144,
    Category: "Milk",
    "Exipry Date (M-Y)": "Oct-22",
    "Unit Price": "$25.00",
  },
  // {
  //   "S/N": 126,
  //   "Brand Name": "Peak",
  //   "Product Name": "Milk",
  //   Quantity: 22,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "400g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 8716200478205,
  //   Category: "Milk",
  //   "Exipry Date (M-Y)": "Jul-22",
  //   "Unit Price": "$10.00",
  // },
  // {
  //   "S/N": 127,
  //   "Brand Name": "Peak",
  //   "Product Name": "Milk",
  //   Quantity: 6,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "2500g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 8716200635783,
  //   Category: "Milk",
  //   "Exipry Date (M-Y)": "Mar-23",
  //   "Unit Price": "$64.00",
  // },
  // {
  //   "S/N": 128,
  //   "Brand Name": "Nestle",
  //   "Product Name": "Milo",
  //   Quantity: 4,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "1kg",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6151100032454,
  //   Category: "Beverage",
  //   "Exipry Date (M-Y)": "Sep-22",
  //   "Unit Price": "$17.50",
  // },
  {
    "S/N": 129,
    "Brand Name": "Nestle",
    "Product Name": "Milo",
    imageSrc: "/milo.jpeg",
    Quantity: 10,
    "Weight (lb)": "-",
    "Weight (kg)": "500g",
    Size: "-",
    "Barcode No/ Product ID": 6151100032393,
    Category: "Beverage",
    "Exipry Date (M-Y)": "Oct-22",
    "Unit Price": "$10.00",
  },
  // {
  //   "S/N": 130,
  //   "Brand Name": "Pears",
  //   "Product Name": "Moisturising Cream",
  //   Quantity: 11,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "300g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6151100138736,
  //   Category: "Cream",
  //   "Exipry Date (M-Y)": "Sep-22",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 131,
  //   "Brand Name": "Pears",
  //   "Product Name": "Moisturising Cream",
  //   imageSrc: "/PEARS-MOISTURISING-BABY-CREAM-300G-6151100138736.jpeg",
  //   Quantity: 12,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "300g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6151100138736,
  //   Category: "Cream",
  //   "Exipry Date (M-Y)": "Nov-22",
  //   "Unit Price": "$5.00",
  // },
  {
    "S/N": 132,
    "Brand Name": "Grain Process Enterprises Ltd",
    "Product Name": "Monarch Wheatlets",
    imageSrc: "/Wheatlets-monarch.jpeg",
    Quantity: 3,
    "Weight (lb)": 22,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "Wheatlets",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$24.00",
  },
  {
    "S/N": 133,
    "Brand Name": "Morgan's",
    imageSrc: "/morgans_pormade.webp",
    "Product Name": "Morgan's Pomade",
    Quantity: 12,
    "Weight (lb)": "-",
    "Weight (kg)": "50g",
    Size: "-",
    "Barcode No/ Product ID": 5012521509998,
    Category: "Cream",
    "Exipry Date (M-Y)": "Jun-25",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 134,
    "Brand Name": "Nestle",
    "Product Name": "Nido Milk",
    imageSrc: "/nido_milk.jpeg",
    Quantity: 12,
    "Weight (lb)": "-",
    "Weight (kg)": "900g",
    Size: "-",
    "Barcode No/ Product ID": "028000469733",
    Category: "Milk",
    "Exipry Date (M-Y)": "Aug-23",
    "Unit Price": "$25.00",
  },
  // {
  //   "S/N": 135,
  //   "Brand Name": "Nestle",
  //   "Product Name": "Nido Milk",
  //   Quantity: 24,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "400g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 8715000998630,
  //   Category: "Milk",
  //   "Exipry Date (M-Y)": "May-23",
  //   "Unit Price": "$12.50",
  // },
  // {
  //   "S/N": 136,
  //   "Brand Name": "Nestle",
  //   "Product Name": "Nido Milk",
  //   Quantity: 5,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "2.5kg",
  //   Size: "-",
  //   "Barcode No/ Product ID": 8715000931842,
  //   Category: "Milk",
  //   "Exipry Date (M-Y)": "Aug-23",
  //   "Unit Price": "$64.20",
  // },
  // {
  //   "S/N": 137,
  //   "Brand Name": "Tahitian",
  //   "Product Name": "Noni",
  //   Quantity: 10,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "60ml",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$55.00",
  // },
  {
    "S/N": 138,
    "Brand Name": "Tahitian",
    "Product Name": "Noni",
    imageSrc: "/tahitian_noni.png",
    Quantity: 4,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "1 Litre",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "May-23",
    "Unit Price": "$8.00",
  },
  {
    "S/N": 139,
    "Brand Name": "Haansbro",
    "Product Name": "Noreos",
    Quantity: "-",
    imageSrc: "/noreos.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 5060482954135,
    Category: "Biscuit",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 140,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Nutmeg (Grounded)",
    Quantity: 25,
    "Weight (lb)": "-",
    "Weight (kg)": "60g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 141,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Nutmeg (Ungrounded)",
    Quantity: 11,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 142,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ofada Rice",
    Quantity: 31,
    "Weight (lb)": 5.5,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7555580029987,
    Category: "Rice",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$14.00",
  },
  {
    "S/N": 143,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ofada Rice",
    Quantity: 108,
    "Weight (lb)": 2.2,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 9665870662577,
    Category: "Rice",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 144,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ofada Rice (High Grade)",
    Quantity: 37,
    "Weight (lb)": 5.5,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 8880225677490,
    Category: "Rice",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$20.00",
  },
  {
    "S/N": 145,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ogbono Seed (Grounded)",
    Quantity: 32,
    "Weight (lb)": "-",
    "Weight (kg)": "300g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 146,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Ogbono Seed (Ungrounded)",
    Quantity: 31,
    "Weight (lb)": "-",
    "Weight (kg)": "150g",
    Size: "-",
    "Barcode No/ Product ID": 7000556665510,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 147,
    "Brand Name": "Tasty Pot",
    "Product Name": "Ogi (Pap) Guinea Corn",
    Quantity: 15,
    imageSrc: "/tasty_pot.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "500g",
    Size: "-",
    "Barcode No/ Product ID": 703510548924,
    Category: "",
    "Exipry Date (M-Y)": "Oct-23",
    "Unit Price": "$6.00",
  },
  // {
  //   "S/N": 148,
  //   "Brand Name": "Tasty Pot",
  //   "Product Name": "Ogi (Pap) White Maize",
  //   Quantity: 9,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "500g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 703510548955,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Mar-23",
  //   "Unit Price": "$6.00",
  // },
  // {
  //   "S/N": 149,
  //   "Brand Name": "Tasty Pot",
  //   "Product Name": "Ogi (Pap) Yellow Maize",
  //   Quantity: 15,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "500g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 703510548948,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Mar-23",
  //   "Unit Price": "$6.00",
  // },
  {
    "S/N": 150,
    "Brand Name": "Goya",
    "Product Name": "Olive Oil",
    imageSrc: "/goya.webp",
    Quantity: 72,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "89ml",
    "Barcode No/ Product ID": "041331011037",
    Category: "",
    "Exipry Date (M-Y)": "Jun-22",
    "Unit Price": "$10.00",
  },
  // {
  //   "S/N": 151,
  //   "Brand Name": "Goya",
  //   "Product Name": "Olive Oil (Box)",
  //   Quantity: 2,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "89ml/Bottle 36 Bottles/Box",
  //   "Barcode No/ Product ID": 10041331011034,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Sep-22",
  //   "Unit Price": "$300.00",
  // },
  {
    "S/N": 152,
    "Brand Name": "Onga",
    "Product Name": "Onga Classic",
    imageSrc: "/onga.png",
    Quantity: 31,
    "Weight (lb)": "-",
    "Weight (kg)": "60g",
    Size: "-",
    "Barcode No/ Product ID": 6008155010176,
    Category: "",
    "Exipry Date (M-Y)": "Oct-22",
    "Unit Price": "$1.00",
  },
  // {
  //   "S/N": 153,
  //   "Brand Name": "Onga",
  //   "Product Name": "Onga Classic (Box)",
  //   Quantity: 4,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "60g/Sachets",
  //   Size: "50 Sachets/Box",
  //   "Barcode No/ Product ID": 26008155010170,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Nov-22",
  //   "Unit Price": "$50.00",
  // },
  {
    "S/N": 154,
    "Brand Name": "Onga",
    "Product Name": "Onga Stew (Box)",
    Quantity: 2,
    imageSrc: "/onga_stew.png",
    "Weight (lb)": "-",
    "Weight (kg)": "60g/Sachets",
    Size: "50 Sachets/Box",
    "Barcode No/ Product ID": 26008155010163,
    Category: "",
    "Exipry Date (M-Y)": "Jul-22",
    "Unit Price": "$50.00",
  },
  // {
  //   "S/N": 155,
  //   "Brand Name": "Onga",
  //   "Product Name": "Onga Stew (Box)",
  //   Quantity: 3,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "60g/Sachets",
  //   Size: "50 Sachets/Box",
  //   "Barcode No/ Product ID": 26008155010163,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Sep-22",
  //   "Unit Price": "$50.00",
  // },
  {
    "S/N": 156,
    "Brand Name": "Dettol",
    "Product Name": "Original Antibacterial Bar Soap",
    Quantity: 12,
    imageSrc: "/dettol_original.webp",
    "Weight (lb)": "-",
    "Weight (kg)": "110g",
    Size: "-",
    "Barcode No/ Product ID": 6151100280466,
    Category: "Soap",
    "Exipry Date (M-Y)": "Dec-22",
    "Unit Price": "$3.00",
  },
  // {
  //   "S/N": 157,
  //   "Brand Name": "Dettol",
  //   "Product Name": "Original Antibacterial Bar Soap",
  //   Quantity: 132,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "65g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6151100280398,
  //   Category: "Soap",
  //   "Exipry Date (M-Y)": "Feb-23",
  //   "Unit Price": "$1.99",
  // },
  {
    "S/N": 158,
    "Brand Name": "Ovaltine",
    "Product Name": "Ovaltine",
    Quantity: 11,
    imageSrc: "/ovaltine.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "400g",
    Size: "-",
    "Barcode No/ Product ID": 7612100066232,
    Category: "Beverage",
    "Exipry Date (M-Y)": "Jan-23",
    "Unit Price": "$12.00",
  },
  // {
  //   "S/N": 159,
  //   "Brand Name": "Ovaltine",
  //   "Product Name": "Ovaltine",
  //   Quantity: 20,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "400g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 7612100066232,
  //   Category: "Beverage",
  //   "Exipry Date (M-Y)": "Apr-23",
  //   "Unit Price": "$12.00",
  // },
  // {
  //   "S/N": 160,
  //   "Brand Name": "Ovaltine",
  //   "Product Name": "Ovaltine (Box)",
  //   Quantity: 1,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "400g/Tin",
  //   Size: "12 Tins/Box",
  //   "Barcode No/ Product ID": 6906791111045,
  //   Category: "Beverage",
  //   "Exipry Date (M-Y)": "Jan-23",
  //   "Unit Price": "$96.00",
  // },
  {
    "S/N": 161,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Pako-Ijebu (Chewing Stick)",
    Quantity: 93,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "-",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$2.00",
  },
  {
    "S/N": 162,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Palm Oil",
    Quantity: 6,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "4 Litres",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$25.00",
  },
  {
    "S/N": 163,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Palm Oil",
    Quantity: 6,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "2 Litres",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$12.50",
  },
  {
    "S/N": 164,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Palm Oil",
    Quantity: 11,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "1 Litre",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$7.00",
  },
  {
    "S/N": 165,
    "Brand Name": "Parle",
    "Product Name": "Parle G",
    Quantity: "-",
    imageSrc: "/parle-g.jpeg",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 8901719916861,
    Category: "Biscuit",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$1.00",
  },
  // {
  //   "S/N": 166,
  //   "Brand Name": "Ola's Yommy",
  //   "Product Name": "Peanut Cookies (Kuli Kuli)",
  //   Quantity: 192,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "Kuli Kuli",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  {
    "S/N": 167,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Peanut Snacks (Groundnut)",
    Quantity: 17,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 7556780025557,
    Category: "Groundnut",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 168,
    "Brand Name": "Timtem African Foods",
    "Product Name": "Peeled Beans",
    imageSrc: "/timtem-peeled-beans-scaled.webp",
    Quantity: 4,
    "Weight (lb)": 2,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "0805627337245",
    Category: "Beans",
    "Exipry Date (M-Y)": "Oct-23",
    "Unit Price": "$15.00",
  },
  // {
  //   "S/N": 169,
  //   "Brand Name": "Timtem African Foods",
  //   "Product Name": "Peeled Beans",
  //   Quantity: 5,
  //   "Weight (lb)": 4,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6156000720227,
  //   Category: "Beans",
  //   "Exipry Date (M-Y)": "Oct-23",
  //   "Unit Price": "$10.00",
  // },
  {
    "S/N": 170,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Pepper Soup Spice",
    Quantity: 19,
    "Weight (lb)": "-",
    "Weight (kg)": "300g",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$10.00",
  },
  {
    "S/N": 171,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Pepper Soup Spice",
    Quantity: 48,
    "Weight (lb)": "-",
    "Weight (kg)": "100g",
    Size: "-",
    "Barcode No/ Product ID": 7556780022228,
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 172,
    "Brand Name": "Vaseline",
    "Product Name": "Petroleum Jelly",
    Quantity: 36,
    imageSrc: "/vaseline.jpg",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "250ml",
    "Barcode No/ Product ID": 6151100139528,
    Category: "Cream",
    "Exipry Date (M-Y)": "May-24",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 173,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Plantain Flour",
    Quantity: 19,
    "Weight (lb)": 2.2,
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": 9665870862533,
    Category: "Flour",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "",
  },
  {
    "S/N": 174,
    "Brand Name": "Stella",
    "Product Name": "Pomade",
    Quantity: 6,
    imageSrc: "/stella-pomade.jpg",
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "125ml",
    "Barcode No/ Product ID": "-",
    Category: "Cream",
    "Exipry Date (M-Y)": "Feb-24",
    "Unit Price": "$5.00",
  },
  {
    "S/N": 175,
    "Brand Name": "Tom & Mercy Best Food",
    "Product Name": "Poroporo",
    Quantity: 22,
    "Weight (lb)": "-",
    "Weight (kg)": "-",
    Size: "-",
    "Barcode No/ Product ID": "-",
    Category: "",
    "Exipry Date (M-Y)": "-",
    "Unit Price": "$5.00",
  },
  // {
  //   "S/N": 176,
  //   "Brand Name": "Ola-Ola",
  //   "Product Name": "Pounded Yam Flour (Iyan)",
  //   Quantity: 2,
  //   imageSrc: "/olaola.png",
  //   "Weight (lb)": 18.5,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 650655241855,
  //   Category: "Flour",
  //   "Exipry Date (M-Y)": "Dec-24",
  //   "Unit Price": "$55.00",
  // },
  // {
  //   "S/N": 177,
  //   "Brand Name": "Ola-Ola",
  //   "Product Name": "Pounded Yam Flour (Iyan)",
  //   Quantity: 8,
  //   "Weight (lb)": 10,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 650655244702,
  //   Category: "Flour",
  //   "Exipry Date (M-Y)": "Nov-24",
  //   "Unit Price": "$30.00",
  // },
  // {
  //   "S/N": 178,
  //   "Brand Name": "Ola-Ola",
  //   "Product Name": "Pounded Yam Flour (Iyan)",
  //   Quantity: 39,
  //   "Weight (lb)": 5,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 650655244856,
  //   Category: "Flour",
  //   "Exipry Date (M-Y)": "Jul-23",
  //   "Unit Price": "$10.00",
  // },
  // {
  //   "S/N": 179,
  //   "Brand Name": "Ayoola",
  //   "Product Name": "Poundo Yam Flour",
  //   Quantity: 9,
  //   "Weight (lb)": 4,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6151100001061,
  //   Category: "Flour",
  //   "Exipry Date (M-Y)": "Jan-23",
  //   "Unit Price": "$5.39",
  // },
  // {
  //   "S/N": 180,
  //   "Brand Name": "Ayoola",
  //   "Product Name": "Poundo Yam Flour",
  //   Quantity: 58,
  //   "Weight (lb)": 2,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6151100001023,
  //   Category: "Flour",
  //   "Exipry Date (M-Y)": "Jan-23",
  //   "Unit Price": "$3.35",
  // },
  // {
  //   "S/N": 181,
  //   "Brand Name": "Fresh",
  //   "Product Name": "Powder Juice (Banana Flavour)",
  //   Quantity: 2,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "1.5 litres",
  //   "Barcode No/ Product ID": 8682655010461,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 182,
  //   "Brand Name": "Viva",
  //   "Product Name": "Powder Juice (Berries Flavour)",
  //   Quantity: 2,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "1.5 litres",
  //   "Barcode No/ Product ID": 8681161902949,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 183,
  //   "Brand Name": "Viva",
  //   "Product Name": "Powder Juice (Coconut Flavour)",
  //   Quantity: 2,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "1.5 litres",
  //   "Barcode No/ Product ID": 8681161905261,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 184,
  //   "Brand Name": "Fresh",
  //   "Product Name": "Powder Juice (Cola kola Flavour)",
  //   Quantity: 3,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "1.5 litres",
  //   "Barcode No/ Product ID": 8681161900273,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 185,
  //   "Brand Name": "Fresh",
  //   "Product Name": "Powder Juice (Pineapple & Coconut Flavour)",
  //   Quantity: 2,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "1.5 litres",
  //   "Barcode No/ Product ID": 8697442106395,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 186,
  //   "Brand Name": "Viva",
  //   "Product Name": "Powder Juice (Pineapple Flavour)",
  //   Quantity: 7,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "1.5 litres",
  //   "Barcode No/ Product ID": 8681161902987,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 187,
  //   "Brand Name": "Viva",
  //   "Product Name": "Powder Juice (Strawberry Flavour)",
  //   Quantity: 6,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "1.5 litres",
  //   "Barcode No/ Product ID": 8681161902963,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 188,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Prawn",
  //   Quantity: 19,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "100g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 7000556665725,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 189,
  //   "Brand Name": "Par Excellence",
  //   "Product Name": "Premium Parboiled Rice",
  //   Quantity: 4,
  //   "Weight (lb)": 100,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "Rice",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$68.00",
  // },
  // {
  //   "S/N": 190,
  //   "Brand Name": "Par Excellence",
  //   "Product Name": "Premium Parboiled Rice",
  //   Quantity: 4,
  //   "Weight (lb)": 50,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "072806056031",
  //   Category: "Rice",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$39.00",
  // },
  // {
  //   "S/N": 191,
  //   "Brand Name": "Par Excellence",
  //   "Product Name": "Premium Parboiled Rice",
  //   Quantity: 3,
  //   "Weight (lb)": 25,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "072806056499",
  //   Category: "Rice",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$24.00",
  // },
  // {
  //   "S/N": 192,
  //   "Brand Name": "Tiger",
  //   "Product Name": "Razor Blade (Pack)",
  //   Quantity: 5,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "100 Blades/Pack",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$3.99",
  // },
  // {
  //   "S/N": 193,
  //   "Brand Name": "Robb",
  //   "Product Name": "Robb",
  //   Quantity: 9,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "25ml",
  //   "Barcode No/ Product ID": 6033000102584,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Jan-24",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 194,
  //   "Brand Name": "Robb",
  //   "Product Name": "Robb (Pack)",
  //   Quantity: 7,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "25ml/Bottle 12 Bottle/Pack",
  //   "Barcode No/ Product ID": 6033000101983,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Jan-24",
  //   "Unit Price": "",
  // },
  // {
  //   "S/N": 195,
  //   "Brand Name": "Heinz",
  //   "Product Name": "Salad Cream",
  //   Quantity: 9,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "285g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 50157228,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Oct-22",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 196,
  //   "Brand Name": "Titus",
  //   "Product Name": "Sardine in Soybean Oil",
  //   Quantity: 50,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "125g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6111239000236,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Oct-25",
  //   "Unit Price": "$6.00",
  // },
  // {
  //   "S/N": 197,
  //   "Brand Name": "Titus",
  //   "Product Name": "Sardine in Vegetable Oil",
  //   Quantity: 36,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "125g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6111239500026,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Jan-25",
  //   "Unit Price": "$10.00",
  // },
  // {
  //   "S/N": 198,
  //   "Brand Name": "Titus",
  //   "Product Name": "Sardine in Vegetable Oil (Box)",
  //   Quantity: 1,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6111239500026,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Jan-25",
  //   "Unit Price": "",
  // },
  // {
  //   "S/N": 199,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Scrubbing Stone",
  //   Quantity: 1,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "",
  //   Size: "1 Bag",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$2.00",
  // },
  // {
  //   "S/N": 200,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Shea Butter",
  //   Quantity: 48,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "100g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 7556780086350,
  //   Category: "Cream",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 201,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Shea Butter",
  //   Quantity: 140,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "100g",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "Cream",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 204,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Sobo Leaves",
  //   Quantity: 57,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 205,
  //   "Brand Name": "Pure Heaven",
  //   "Product Name": "Sparkling Drink Red Grape",
  //   Quantity: 60,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "750ml",
  //   "Barcode No/ Product ID": 5032619311623,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$2.99",
  // },
  // {
  //   "S/N": 206,
  //   "Brand Name": "Yale",
  //   "Product Name": "Speedy Mini Cookies",
  //   Quantity: "-",
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "Biscuit",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$1.00",
  // },
  // {
  //   "S/N": 207,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Sponge",
  //   Quantity: "-",
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 208,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Suya Pepper",
  //   Quantity: 37,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "300g",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$7.00",
  // },
  // {
  //   "S/N": 209,
  //   "Brand Name": "Tasty Cubes",
  //   "Product Name": "Tasty Cubes Chicken Flavour (Box)",
  //   Quantity: 2,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "600g/Cases",
  //   Size: "24 Cases/Box",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "Sep-22",
  //   "Unit Price": "",
  // },
  // {
  //   "S/N": 210,
  //   "Brand Name": "Tasty Cubes",
  //   "Product Name": "Tasty Cubes Chicken Flavour (Pack)",
  //   Quantity: 24,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "600g",
  //   Size: "60 Cubes/Pack",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "Sep-22",
  //   "Unit Price": "$7.00",
  // },
  // {
  //   "S/N": 211,
  //   "Brand Name": "Tasty Cubes",
  //   "Product Name": "Tasty Cubes Crayfish Flavour (Pack)",
  //   Quantity: 45,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "600g",
  //   Size: "60 Cubes/Pack",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "Dec-22",
  //   "Unit Price": "$7.00",
  // },
  // {
  //   "S/N": 212,
  //   "Brand Name": "Gino",
  //   "Product Name": "Tomato",
  //   Quantity: 24,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "400g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 4897052892556,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 213,
  //   "Brand Name": "Gino",
  //   "Product Name": "Tomato",
  //   Quantity: 26,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "210g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 4897052892549,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$3.00",
  // },
  // {
  //   "S/N": 214,
  //   "Brand Name": "De Rica",
  //   "Product Name": "Tomato Paste",
  //   Quantity: 20,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "400g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 8885002835346,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "May-23",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 215,
  //   "Brand Name": "De Rica",
  //   "Product Name": "Tomato Paste",
  //   Quantity: 40,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "210g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 8885002835308,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "Mar-23",
  //   "Unit Price": "$3.50",
  // },
  // {
  //   "S/N": 216,
  //   "Brand Name": "Star",
  //   "Product Name": "Tomato Paste",
  //   Quantity: 35,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "800g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6942653113536,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "Dec-22",
  //   "Unit Price": "$10.00",
  // },
  // {
  //   "S/N": 217,
  //   "Brand Name": "Star",
  //   "Product Name": "Tomato Paste",
  //   Quantity: 35,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "800g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6942653113536,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "Nov-22",
  //   "Unit Price": "$10.00",
  // },
  // {
  //   "S/N": 218,
  //   "Brand Name": "Star",
  //   "Product Name": "Tomato Paste",
  //   Quantity: 47,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "400g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6942653112812,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "Oct-22",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 219,
  //   "Brand Name": "Star",
  //   "Product Name": "Tomato Paste",
  //   Quantity: 64,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "400g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6942653112812,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "Nov-22",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 220,
  //   "Brand Name": "Star",
  //   "Product Name": "Tomato Paste",
  //   Quantity: 62,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "210g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6942653112805,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "May-23",
  //   "Unit Price": "$3.00",
  // },
  // {
  //   "S/N": 221,
  //   "Brand Name": "Star",
  //   "Product Name": "Tomato Paste",
  //   Quantity: 46,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "210g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6942653112805,
  //   Category: "Tomato Paste",
  //   "Exipry Date (M-Y)": "Jun-23",
  //   "Unit Price": "$3.00",
  // },
  // {
  //   "S/N": 222,
  //   "Brand Name": "TomTom",
  //   "Product Name": "TomTom",
  //   Quantity: 14,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "40 Sweets/Bag",
  //   "Barcode No/ Product ID": 7622201782856,
  //   Category: "Sweets",
  //   "Exipry Date (M-Y)": "May-22",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 223,
  //   "Brand Name": "TomTom",
  //   "Product Name": "TomTom (Box)",
  //   Quantity: 6,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "152g/Bag",
  //   Size: "24 Bags/Box",
  //   "Barcode No/ Product ID": "-",
  //   Category: "Sweets",
  //   "Exipry Date (M-Y)": "Jun-22",
  //   "Unit Price": "$30.00",
  // },
  // {
  //   "S/N": 224,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Turning Stick (Wooden)",
  //   Quantity: 84,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$2 or $5",
  // },
  // {
  //   "S/N": 225,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Ugu Leaves",
  //   Quantity: 16,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 226,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Uha",
  //   Quantity: 12,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "60g",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 227,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Ukazi Leaves",
  //   Quantity: 13,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 228,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Ukwa",
  //   Quantity: 17,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "200g",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 229,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Ukwa",
  //   Quantity: 64,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "100g",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 230,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Uziza",
  //   Quantity: 23,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "60g",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 231,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Uziza Leaves",
  //   Quantity: 10,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 232,
  //   "Brand Name": "Vitamalt",
  //   "Product Name": "Vitamalt (Pack)",
  //   Quantity: 5,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "24 Bottles/Pack",
  //   "Barcode No/ Product ID": 737297000115,
  //   Category: "Drinks",
  //   "Exipry Date (M-Y)": "Oct-22",
  //   "Unit Price": "$35.00",
  // },
  // {
  //   "S/N": 233,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "White Eye Beans",
  //   Quantity: 29,
  //   "Weight (lb)": 2.2,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 8800026667483,
  //   Category: "Beans",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$6.00",
  // },
  // {
  //   "S/N": 234,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "White Garri",
  //   Quantity: 33,
  //   "Weight (lb)": 5.5,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 7557780029989,
  //   Category: "Garri",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 235,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "White Garri",
  //   Quantity: 57,
  //   "Weight (lb)": 2.2,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 7556680029952,
  //   Category: "Garri",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$2.00",
  // },
  // {
  //   "S/N": 236,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "White Garri",
  //   Quantity: 64,
  //   "Weight (lb)": 1.1,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 7556780023331,
  //   Category: "Garri",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$1.00",
  // },
  // {
  //   "S/N": 237,
  //   "Brand Name": "Quaker",
  //   "Product Name": "White Oats",
  //   Quantity: 24,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "500g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 5000108478119,
  //   Category: "",
  //   "Exipry Date (M-Y)": "Apr-23",
  //   "Unit Price": "$6.50",
  // },
  // {
  //   "S/N": 238,
  //   "Brand Name": "Sarah",
  //   "Product Name": "White Prawn Crackers",
  //   Quantity: 61,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "227g",
  //   Size: "-",
  //   "Barcode No/ Product ID": 6921325101286,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 239,
  //   "Brand Name": "Sarah",
  //   "Product Name": "White Prawn Crackers (Box)",
  //   Quantity: 1,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "30 Pieces/Box",
  //   "Barcode No/ Product ID": 6921325101293,
  //   Category: "",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$150.00",
  // },
  // {
  //   "S/N": 240,
  //   "Brand Name": "Whot",
  //   "Product Name": "Whot Cards (Game)",
  //   Quantity: 35,
  //   "Weight (lb)": "-",
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": "-",
  //   Category: "Game",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
  // {
  //   "S/N": 241,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Yam Flour (Elubo)",
  //   Quantity: 30,
  //   "Weight (lb)": 5.5,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 8800025667484,
  //   Category: "Flour",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$12.00",
  // },
  // {
  //   "S/N": 242,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Yam Flour (Elubo)",
  //   Quantity: 119,
  //   "Weight (lb)": 2.2,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 9665870862595,
  //   Category: "Flour",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$6.00",
  // },
  // {
  //   "S/N": 243,
  //   "Brand Name": "Tom & Mercy Best Food",
  //   "Product Name": "Yellow Garri",
  //   Quantity: 73,
  //   "Weight (lb)": 2.2,
  //   "Weight (kg)": "-",
  //   Size: "-",
  //   "Barcode No/ Product ID": 9665870862540,
  //   Category: "Garri",
  //   "Exipry Date (M-Y)": "-",
  //   "Unit Price": "$5.00",
  // },
];

export default data;
